<?php

return [
    'items' => [
        [
            'slug' => 'iphone-15-pro-max-256',
            'name' => 'iPhone 15 Pro Max 256GB',
            'brand' => 'Apple',
            'category' => 'گوشی موبایل',
            'image' => 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=1200',
            'price' => '۹۱,۵۰۰,۰۰۰',
            'old_price' => '۱۰۷,۰۰۰,۰۰۰',
            'badge' => '۱۵٪ تخفیف',
            'description' => 'آیفون ۱۵ پرو مکس با فریم تیتانیومی، دوربین حرفه‌ای ۴۸ مگاپیکسلی و باتری قدرتمند، گزینه‌ای ایده‌آل برای تولید محتوا و استفاده روزمره است.',
            'specs' => [
                'نمایشگر 6.7 اینچ Super Retina XDR',
                'چیپست Apple A17 Pro',
                'دوربین اصلی 48 مگاپیکسل + تله‌فوتو',
                'حافظه داخلی 256 گیگابایت',
            ],
        ],
        [
            'slug' => 'galaxy-s24-ultra-512',
            'name' => 'Samsung Galaxy S24 Ultra 512GB',
            'brand' => 'Samsung',
            'category' => 'گوشی موبایل',
            'image' => 'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=1200',
            'price' => '۷۳,۹۰۰,۰۰۰',
            'old_price' => '۸۰,۰۰۰,۰۰۰',
            'badge' => 'پیشنهاد ویژه',
            'description' => 'گلکسی S24 Ultra با قلم S Pen، دوربین زوم‌دار قوی و نمایشگر بسیار روشن، برای کاربرانی که گوشی همه‌فن‌حریف می‌خواهند مناسب است.',
            'specs' => [
                'نمایشگر 6.8 اینچ Dynamic AMOLED 2X',
                'چیپست Snapdragon 8 Gen 3',
                'دوربین اصلی 200 مگاپیکسل',
                'حافظه داخلی 512 گیگابایت',
            ],
        ],
        [
            'slug' => 'macbook-air-m3-13',
            'name' => 'MacBook Air M3 13"',
            'brand' => 'Apple',
            'category' => 'لپ‌تاپ',
            'image' => 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1200',
            'price' => '۶۶,۴۰۰,۰۰۰',
            'old_price' => '۷۱,۰۰۰,۰۰۰',
            'badge' => 'جدید',
            'description' => 'مک‌بوک ایر M3 با وزن سبک، شارژدهی طولانی و عملکرد سریع، انتخابی عالی برای دانشجوها و برنامه‌نویس‌هاست.',
            'specs' => [
                'نمایشگر 13.6 اینچ Liquid Retina',
                'چیپ Apple M3',
                'رم 16 گیگابایت',
                'حافظه SSD یک ترابایت',
            ],
        ],
        [
            'slug' => 'asus-tuf-gaming-f15',
            'name' => 'ASUS TUF Gaming F15',
            'brand' => 'ASUS',
            'category' => 'لپ‌تاپ گیمینگ',
            'image' => 'https://images.pexels.com/photos/7915577/pexels-photo-7915577.jpeg?auto=compress&cs=tinysrgb&w=1200',
            'price' => '۵۴,۸۰۰,۰۰۰',
            'old_price' => '۵۹,۲۰۰,۰۰۰',
            'badge' => 'محبوب',
            'description' => 'لپ‌تاپ گیمینگ TUF F15 با سیستم خنک‌کنندگی بهبود‌یافته و کارت گرافیک قدرتمند، برای بازی و کارهای سنگین کاملاً مناسب است.',
            'specs' => [
                'پردازنده Intel Core i7 نسل 13',
                'کارت گرافیک NVIDIA RTX 4060',
                'نمایشگر 15.6 اینچ 144Hz',
                'رم 16 گیگابایت DDR5',
            ],
        ],
        [
            'slug' => 'xiaomi-pad-6',
            'name' => 'Xiaomi Pad 6 256GB',
            'brand' => 'Xiaomi',
            'category' => 'تبلت',
            'image' => 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1200',
            'price' => '۱۸,۹۰۰,۰۰۰',
            'old_price' => '۲۱,۰۰۰,۰۰۰',
            'badge' => 'اقتصادی',
            'description' => 'شیائومی پد ۶ با نمایشگر 144 هرتز و بدنه باریک، برای مطالعه، تماشای فیلم و کارهای روزمره یک انتخاب خوش‌قیمت است.',
            'specs' => [
                'نمایشگر 11 اینچ WQHD+ با نرخ 144Hz',
                'پردازنده Snapdragon 870',
                'حافظه داخلی 256 گیگابایت',
                'باتری 8840 میلی‌آمپرساعت',
            ],
        ],
        [
            'slug' => 'sony-wh-1000xm5',
            'name' => 'Sony WH-1000XM5',
            'brand' => 'Sony',
            'category' => 'لوازم جانبی',
            'image' => 'https://images.pexels.com/photos/3394656/pexels-photo-3394656.jpeg?auto=compress&cs=tinysrgb&w=1200',
            'price' => '۱۶,۲۰۰,۰۰۰',
            'old_price' => '۱۸,۱۰۰,۰۰۰',
            'badge' => 'پرفروش',
            'description' => 'هدفون نویزکنسلینگ سونی با کیفیت صدای عالی، مکالمه شفاف و راحتی بالا برای استفاده طولانی‌مدت طراحی شده است.',
            'specs' => [
                'نویز کنسلینگ هوشمند چندمیکروفونه',
                'تا 30 ساعت شارژدهی',
                'پشتیبانی از صدای Hi-Res',
                'اتصال همزمان به دو دستگاه',
            ],
        ],
    ],
];
